export const CUSTOMER_SOURCE_OPTIONS = [
	'Google Ads',
	'Google Maps',
	'Facebook Ads',
	'Facebook / Instagram',
	'TikTok / YouTube',
	'Polecenie / znajomi',
	'Wizytówka / QR',
	'B2B / partner',
	'Oklejony samochód',
	'Offline',
	'Wyszukiwarka Google',
	'Strona internetowa',
	'Inne',
]
